// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID          string
	RefreshTokenHash string
	Role             string
	PublicKey        string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastHeartbeatAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
	ClientCertHash   string
}

type AgentBootstrap struct {
	TokenHash string
	AgentID   string
	UsedAt    pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AgentInstruction struct {
	InstructionID   string
	AgentID         string
	Kind            string
	PayloadRef      string
	Status          string
	LeaseID         string
	LeaseExpiresAt  pgtype.Timestamptz
	CapabilityToken string
	CreatedAt       pgtype.Timestamptz
	Deadline        pgtype.Timestamptz
	AckedAt         pgtype.Timestamptz
	AckError        string
	BudgetID        string
	LeaseEpoch      int64
	TurnID          string
}

type AgentThread struct {
	ThreadID   string
	SourceKind string
	SourceRef  string
	AgentID    string
	CreatedAt  pgtype.Timestamptz
}

type AgentToken struct {
	TokenHash      string
	AgentID        string
	Kind           string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	PubkeyHash     string
	ClientCertHash string
}

type AgentTurn struct {
	TurnID        string
	ThreadID      string
	SourceVersion int64
	InputSnapshot []byte
	State         string
	OutputRef     string
	CreatedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type Asset struct {
	AssetID      string
	DisplayName  string
	AccessMode   string
	Transports   []byte
	Capabilities []byte
	Criticality  string
	MaxAutoTier  string
	Labels       []byte
	LastProbeAt  pgtype.Timestamptz
	Version      int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AssetGeneration struct {
	GenerationID  string
	AssetID       string
	GenerationSeq int64
	Envelope      []byte
	Signed        bool
	CreatedAt     pgtype.Timestamptz
}

type AuditEntry struct {
	Sequence     int64
	OccurredAt   pgtype.Timestamptz
	ActorType    string
	ActorID      string
	Action       string
	ObjectType   string
	ObjectID     string
	Details      []byte
	PreviousHash string
	EntryHash    string
}

type CapabilityBudget struct {
	Jti       string
	Subject   string
	Azp       string
	MaxCalls  int64
	CallsUsed int64
	Revoked   bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	BudgetID  string
}

type CapabilityTokenInstance struct {
	Jti        string
	BudgetID   string
	LeaseID    string
	LeaseEpoch int64
	ExpiresAt  pgtype.Timestamptz
	Revoked    bool
	CreatedAt  pgtype.Timestamptz
}

type Command struct {
	CommandID      string
	UnitID         string
	RunID          string
	ProcedureRef   string
	ArtifactRef    string
	TargetAssetID  string
	Steps          []byte
	Deadline       pgtype.Timestamptz
	Status         string
	LeaseID        string
	LeaseDeadline  pgtype.Timestamptz
	ResultJson     string
	IdempotencyKey string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CredentialSlot struct {
	SlotID           string
	Kind             string
	SecretHash       string
	SecretCiphertext []byte
	SecretHint       string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type DenyFeedback struct {
	ReleaseID string
	EventID   string
	Actor     string
	Note      string
	CreatedAt pgtype.Timestamptz
}

type DeploymentOnboarding struct {
	ID                   int16
	State                string
	LocalAssetID         string
	UpdatedAt            pgtype.Timestamptz
	BaseUrl              string
	Model                string
	LastError            string
	ModelLive            bool
	Dialect              string
	DeploymentSpec       []byte
	DeploymentSpecDigest string
}

type Event struct {
	EventID       string
	UnitID        string
	AssetID       string
	RequestID     string
	OccurredAt    pgtype.Timestamptz
	IngestedAt    pgtype.Timestamptz
	Source        string
	Kind          string
	Verdict       string
	Payload       []byte
	ReleaseTraces []byte
	Observation   string
	TriageReason  string
	ClusterID     string
	GenerationSeq int64
	PayloadDigest string
}

type Grant struct {
	GrantID     string
	SubjectKind string
	SubjectID   string
	Tools       []byte
	Bindings    []byte
	CreatedBy   string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type IdempotencyKey struct {
	Scope         string
	IdemKey       string
	RequestDigest string
	StatusCode    string
	ResponseJson  []byte
	CreatedAt     pgtype.Timestamptz
}

type ModelGatewayCall struct {
	ID         int64
	OccurredAt pgtype.Timestamptz
	Kind       string
	Ok         bool
	Host       string
	Model      string
	LatencyMs  int32
	Error      string
}

type ModelInference struct {
	InferenceID     string
	EventID         string
	ModelGroup      string
	ModelType       string
	ModelVersion    string
	Threshold       float64
	Score           float64
	AttackClass     string
	TaxonomyVersion string
	RecordedAt      pgtype.Timestamptz
}

type Outbox struct {
	OutboxID    int64
	Topic       string
	DedupeKey   string
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	Attempts    int32
}

type Release struct {
	ReleaseID       string
	State           string
	ArtifactID      string
	Artifact        []byte
	Supersedes      string
	TtlSeconds      int64
	CanaryPercent   int32
	CreatedBy       string
	ProposedAt      pgtype.Timestamptz
	SignedAt        pgtype.Timestamptz
	ShadowStartedAt pgtype.Timestamptz
	CanaryStartedAt pgtype.Timestamptz
	EnforcedAt      pgtype.Timestamptz
	RetiredAt       pgtype.Timestamptz
	RetireReason    string
	UpdatedAt       pgtype.Timestamptz
	ReviewAt        pgtype.Timestamptz
	HardExpiresAt   pgtype.Timestamptz
	ExpiryBehavior  string
	ScopeRisk       string
	EvidenceClass   string
	GenerationSeq   int64
}

type ReleaseAsset struct {
	ReleaseID string
	AssetID   string
}

type ReleaseCounter struct {
	UnitID              string
	ReleaseID           string
	Generation          int64
	Mode                string
	RequestsTotal       int64
	BlocksTotal         int64
	ObserveTotal        int64
	CanarySelectedTotal int64
	Upstream5xxTotal    int64
	LatencyMicrosTotal  int64
	LatencySamples      int64
	UpdatedAt           pgtype.Timestamptz
	LatencyP99Micros    int64
}

type ReleaseFeed struct {
	Seq           int64
	UnitID        string
	AssetID       string
	ReleaseID     string
	Mode          string
	CanaryPercent int32
	Retired       bool
	RetireReason  string
	Artifact      []byte
	ChangedAt     pgtype.Timestamptz
}

type ReleaseGuard struct {
	ReleaseID      string
	RequestsTotal  int64
	BlocksTotal    int64
	DenyTotal      int64
	ConsecutiveBad int32
	LastBadAt      pgtype.Timestamptz
	LastBadReasons string
	UpdatedAt      pgtype.Timestamptz
	LastP99Micros  int64
}

type ReleaseTimeline struct {
	Sequence      int64
	ReleaseID     string
	FromState     string
	ToState       string
	Actor         string
	Reason        string
	GateReportRef string
	OccurredAt    pgtype.Timestamptz
}

type Run struct {
	RunID     string
	State     string
	Role      string
	PlanRef   string
	Toolset   []byte
	Budget    string
	Ttl       string
	Bindings  []byte
	CreatedBy string
	CreatedAt pgtype.Timestamptz
	Deadline  pgtype.Timestamptz
	Error     string
	UpdatedAt pgtype.Timestamptz
}

type RunEvent struct {
	Sequence   int64
	RunID      string
	Kind       string
	PayloadRef string
	OccurredAt pgtype.Timestamptz
}

type Session struct {
	SessionID string
	Title     string
	Owner     string
	CreatedAt pgtype.Timestamptz
}

type SessionMessage struct {
	Sequence   int64
	SessionID  string
	Sender     string
	Content    string
	OccurredAt pgtype.Timestamptz
}

type TriageCluster struct {
	ClusterID      string
	AssetID        string
	RouteTemplate  string
	Method         string
	IdentityKey    string
	Reason         string
	EventIds       []byte
	Representative string
	OpenedAt       pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	ClosedAt       pgtype.Timestamptz
	Version        int64
}

type TriageDecision struct {
	DecisionID     string
	TurnID         string
	AgentID        string
	DecisionDigest string
	Decision       []byte
	ReleaseID      string
	Result         []byte
	CreatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type Unit struct {
	UnitID               string
	Kind                 string
	Version              string
	ContractVersion      string
	PubkeyHint           string
	TokenHash            string
	Health               string
	Generation           int64
	LastHeartbeatAt      pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	RefreshTokenHash     string
	RefreshExpiresAt     pgtype.Timestamptz
	TokenExpiresAt       pgtype.Timestamptz
	ProducerCapabilities []byte
	ProducerHealth       []byte
	Posture              string
	TrafficKey           string
}

type UnitAsset struct {
	UnitID    string
	AssetID   string
	Relation  string
	IsPrimary bool
	CreatedAt pgtype.Timestamptz
}

type UnitListenPlan struct {
	UnitID    string
	Version   int64
	Envelope  []byte
	Signed    bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	UserID       string
	Username     string
	DisplayName  string
	Role         string
	State        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
}

type UserSession struct {
	TokenHash string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type WorkItem struct {
	WorkID          string
	RunID           string
	WorkerID        string
	LeaseID         string
	LeaseDeadline   pgtype.Timestamptz
	CapabilityToken string
	Status          string
	ResultRef       string
	Receipt         string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	BudgetID        string
	LeaseEpoch      int64
}

type Worker struct {
	WorkerID         string
	CapabilityLabels []byte
	Version          string
	Bindings         []byte
	UpdatedAt        pgtype.Timestamptz
}
