// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets
`

func (q *Queries) CountAssets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, display_name, role, state, created_at, updated_at, last_login_at, password_hash
FROM users WHERE username = $1
`

type GetUserByUsernameRow struct {
	UserID       string
	Username     string
	DisplayName  string
	Role         string
	State        string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
	PasswordHash string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
	)
	return i, err
}

const listActiveReleasesForUnit = `-- name: ListActiveReleasesForUnit :many
SELECT r.release_id, r.artifact, r.state, r.canary_percent, ua.asset_id, r.updated_at
FROM releases r
JOIN release_assets ra ON ra.release_id = r.release_id
JOIN unit_assets ua ON ua.asset_id = ra.asset_id
WHERE ua.unit_id = $1 AND r.state IN ('shadow','canary','enforce')
ORDER BY r.updated_at
`

type ListActiveReleasesForUnitRow struct {
	ReleaseID     string
	Artifact      []byte
	State         string
	CanaryPercent int32
	AssetID       string
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) ListActiveReleasesForUnit(ctx context.Context, unitID string) ([]ListActiveReleasesForUnitRow, error) {
	rows, err := q.db.Query(ctx, listActiveReleasesForUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveReleasesForUnitRow
	for rows.Next() {
		var i ListActiveReleasesForUnitRow
		if err := rows.Scan(
			&i.ReleaseID,
			&i.Artifact,
			&i.State,
			&i.CanaryPercent,
			&i.AssetID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEvents = `-- name: ListRecentEvents :many
SELECT event_id, unit_id, asset_id, request_id, occurred_at, source, kind, verdict, payload
FROM events ORDER BY occurred_at DESC LIMIT $1
`

type ListRecentEventsRow struct {
	EventID    string
	UnitID     string
	AssetID    string
	RequestID  string
	OccurredAt pgtype.Timestamptz
	Source     string
	Kind       string
	Verdict    string
	Payload    []byte
}

func (q *Queries) ListRecentEvents(ctx context.Context, limit int32) ([]ListRecentEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentEventsRow
	for rows.Next() {
		var i ListRecentEventsRow
		if err := rows.Scan(
			&i.EventID,
			&i.UnitID,
			&i.AssetID,
			&i.RequestID,
			&i.OccurredAt,
			&i.Source,
			&i.Kind,
			&i.Verdict,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
